<?php
// Automatically Generated by TestLink Installer - Mon, 02 Sep 24 15:12:05 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'pwd_root');
define('DB_HOST', '172.22.6.23');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
